module.exports = (io, eventBus, room, roomData, players) => {
    console.log(`Initializing kingdomino for room: ${room}`);

    const colors = ["red", "blue", "green", "yellow"];
    const tiles = {
        1: { left: { type: "farm", crown: 0 }, right: { type: "farm", crown: 0 }, asset: "1.png" },
        2: { left: { type: "farm", crown: 0 }, right: { type: "farm", crown: 0 }, asset: "1.png" },
        3: { left: { type: "forest", crown: 0 }, right: { type: "forest", crown: 0 }, asset: "3.png" },
        4: { left: { type: "forest", crown: 0 }, right: { type: "forest", crown: 0 }, asset: "3.png" },
        5: { left: { type: "forest", crown: 0 }, right: { type: "forest", crown: 0 }, asset: "3.png" },
        6: { left: { type: "forest", crown: 0 }, right: { type: "forest", crown: 0 }, asset: "3.png" },
        7: { left: { type: "water", crown: 0 }, right: { type: "water", crown: 0 }, asset: "8.png" },
        8: { left: { type: "water", crown: 0 }, right: { type: "water", crown: 0 }, asset: "8.png" },
        9: { left: { type: "water", crown: 0 }, right: { type: "water", crown: 0 }, asset: "8.png" },
        10: { left: { type: "plains", crown: 0 }, right: { type: "plains", crown: 0 }, asset: "10.png" },
        11: { left: { type: "plains", crown: 0 }, right: { type: "plains", crown: 0 }, asset: "10.png" },
        12: { left: { type: "wasteland", crown: 0 }, right: { type: "wasteland", crown: 0 }, asset: "12.png" },
        13: { left: { type: "farm", crown: 0 }, right: { type: "forest", crown: 0 }, asset: "13.png" },
        14: { left: { type: "farm", crown: 0 }, right: { type: "water", crown: 0 }, asset: "14.png" },
        15: { left: { type: "farm", crown: 0 }, right: { type: "plains", crown: 0 }, asset: "15.png" },
        16: { left: { type: "farm", crown: 0 }, right: { type: "wasteland", crown: 0 }, asset: "16.png" },
        17: { left: { type: "forest", crown: 0 }, right: { type: "water", crown: 0 }, asset: "17.png" },
        18: { left: { type: "forest", crown: 0 }, right: { type: "plains", crown: 0 }, asset: "18.png" },
        19: { left: { type: "farm", crown: 1 }, right: { type: "forest", crown: 0 }, asset: "19.png" },
        20: { left: { type: "farm", crown: 1 }, right: { type: "water", crown: 0 }, asset: "20.png" },
        21: { left: { type: "farm", crown: 1 }, right: { type: "plains", crown: 0 }, asset: "21.png" },
        22: { left: { type: "farm", crown: 1 }, right: { type: "wasteland", crown: 0 }, asset: "22.png" },
        23: { left: { type: "farm", crown: 1 }, right: { type: "mine", crown: 0 }, asset: "23.png" },
        24: { left: { type: "forest", crown: 1 }, right: { type: "farm", crown: 0 }, asset: "24.png" },
        25: { left: { type: "forest", crown: 1 }, right: { type: "farm", crown: 0 }, asset: "24.png" },
        26: { left: { type: "forest", crown: 1 }, right: { type: "farm", crown: 0 }, asset: "24.png" },
        27: { left: { type: "forest", crown: 1 }, right: { type: "farm", crown: 0 }, asset: "24.png" },
        28: { left: { type: "forest", crown: 1 }, right: { type: "water", crown: 0 }, asset: "28.png" },
        29: { left: { type: "forest", crown: 1 }, right: { type: "plains", crown: 0 }, asset: "29.png" },
        30: { left: { type: "water", crown: 1 }, right: { type: "farm", crown: 0 }, asset: "30.png" },
        31: { left: { type: "water", crown: 1 }, right: { type: "farm", crown: 0 }, asset: "30.png" },
        32: { left: { type: "water", crown: 1 }, right: { type: "forest", crown: 0 }, asset: "32.png" },
        33: { left: { type: "water", crown: 1 }, right: { type: "forest", crown: 0 }, asset: "32.png" },
        34: { left: { type: "water", crown: 1 }, right: { type: "forest", crown: 0 }, asset: "32.png" },
        35: { left: { type: "water", crown: 1 }, right: { type: "forest", crown: 0 }, asset: "32.png" },
        36: { left: { type: "farm", crown: 0 }, right: { type: "plains", crown: 1 }, asset: "36.png" },
        37: { left: { type: "water", crown: 0 }, right: { type: "plains", crown: 1 }, asset: "37.png" },
        38: { left: { type: "farm", crown: 0 }, right: { type: "wasteland", crown: 1 }, asset: "38.png" },
        39: { left: { type: "plains", crown: 0 }, right: { type: "wasteland", crown: 1 }, asset: "39.png" },
        40: { left: { type: "mine", crown: 1 }, right: { type: "farm", crown: 0 }, asset: "40.png" },
        41: { left: { type: "farm", crown: 0 }, right: { type: "plains", crown: 2 }, asset: "41.png" },
        42: { left: { type: "water", crown: 0 }, right: { type: "plains", crown: 2 }, asset: "42.png" },
        43: { left: { type: "farm", crown: 0 }, right: { type: "wasteland", crown: 2 }, asset: "43.png" },
        44: { left: { type: "plains", crown: 0 }, right: { type: "wasteland", crown: 2 }, asset: "44.png" },
        45: { left: { type: "mine", crown: 2 }, right: { type: "farm", crown: 0 }, asset: "45.png" },
        46: { left: { type: "wasteland", crown: 0 }, right: { type: "mine", crown: 2 }, asset: "46.png" },
        47: { left: { type: "wasteland", crown: 0 }, right: { type: "mine", crown: 2 }, asset: "46.png" },
        48: { left: { type: "farm", crown: 0 }, right: { type: "mine", crown: 3 }, asset: "48.png" },
    };

    

};